name: SimpleTeleportRequests
version: '${project.version}'
main: simplexity.simpleteleportrequests.SimpleTeleportRequests
api-version: '1.21.5'
permissions:
  teleport.basic:
    default: true
    description: Allows basic functionality of teleport requests and accept
