name: SimpleTeleportRequests
version: '${project.version}'
main: simplexity.simpleteleportrequests.SimpleTeleportRequests
api-version: '1.20.5'
commands:
  tpa:
    permission: teleport.basic
    description: Allows user to request to teleport to someone else
  tpaccept:
    permission: teleport.basic
    description: Allows user to accept requests
  tpahere:
    permission: teleport.basic
    description: allows user to request someone to teleport to them
permissions:
  teleport.basic:
    default: true
    description: Allows basic functionality of teleport requests and accept
